# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: "true"

      - name: checkoutLFS
        uses: actions/checkout@v2
      - run: git lfs pull
          
      - id: set_var
        run: |
         echo $GITHUB_RUN_NUMBER
         echo $GITHUB_REF
         githubjson=`cat package.json`
         number=`echo $(jq -r '.version' <<< "$githubjson")`
         echo $number
         echo "::set-env name=version::${number}"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saurabh210/testingbuild
          tag_with_ref: true
          tags: ${{ env.version  }}-${{ github.run_number }}
